{% set name = "sbank" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07f6b1491c2575603cafaceb65698244c3ab9898209933f83e919b66b08b725b
  patches:
    # -- These patches live on the conda-patches branch of duncanmmacleod's fork
    #    of the gwastro/sbank repo. To see them, go here:
    #
    #    https://github.com/gwastro/sbank/compare/master...duncanmmacleod:sbank:conda-patches
    #
    #    To update them, check out that branch, rebase against the relevant release
    #    tag, then update the commits. To generate new patch files for this feedstock:
    #
    #    git format-patch <tag>
    #
    #    e.g. `git format-patch 1.0.2`
    #
    # clean requirements
    - 0001-remove-lalsuite-from-requirements.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - liblal 7.1
    - numpy
    - pip
    - python
    - setuptools >=30.3.0
  run:
    - h5py
    - lalapps
    - liblal
    - lscsoft-glue
    - matplotlib-base
    - python
    - python-lal
    - python-lalsimulation
    - python-ligo-lw
    - scipy
    - six

test:
  imports:
    - sbank
    - sbank.overlap_cpu
  requires:
    - pip
    - pytest
  commands:
    # check dependencies
    - python -m pip check
    # run unit tests
    - python -m pytest -ra --pyargs sbank.tests
    # sanity check scripts
    - sbank --help

about:
  home: https://github.com/gwastro/sbank/
  dev_url: https://github.com/gwastro/sbank.git
  summary: CBC SBank
  license: GPL-2.0-or-later
  license_file: COPYING
  description: |
    Generate a template bank for searches for gravitational waves
    from compact binary mergers covering a region of mass and spin
    parameter space.

extra:
  recipe-maintainers:
    - duncanmmacleod
